version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD:
      MYSQL_DATABASE: Yii2-database
  mariadb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Yii2-database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - /path/to/store/database:/var/lib/mysql
    ports:
      - "3306:3306"
